name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Generate Snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SANDEEPxKOMMINENI
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: '#4CAF50'
          
      # Generate dark mode snake
      - uses: Platane/snk@master
        id: snake-gif-dark
        with:
          github_user_name: SANDEEPxKOMMINENI
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: '#37BCF6'
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}