name: Spotify Recently Played README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-spotify:
    name: Update Spotify Recently Played
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kittinan/spotify-github-profile@master
        with:
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}